<?php echo $this->doctype(Zend_View_Helper_Doctype::XHTML5); ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle(); ?>
<?php echo $this->headStyle(); ?>
<?php echo $this->headLink(); ?>
<script type="text/javascript"
	src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
<?php echo $this->headScript(); ?>
</head>
<body>
<div class="container"><?php echo $this->layout()->content; ?></div>
</body>
</html>
